name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Swift App
      run: swift build -v
    - name: Create App Bundle
      run: python3 create_app.py
    - name: Upload App Artifact
      uses: actions/upload-artifact@v3
      with:
        name: NookPlayer
        path: NookPlayer.app
